chore(eol): remove PHP 7.0/7.1 from pipeline
newrelic/newrelic-php-agent pull request #907
Opened 2024-05-29 17:04 UTC by bduranleau-nr

EOL PHP 7.0 & 7.1.

2024-05-29 17:21 UTC, zsistla commented
Can also remove this clause: https://github.com/newrelic/newrelic-php-agent/pull/907/files#diff-3c1e3ffee56642b2a90c941707a5ae7f973bda43f91dc3788e8873e95cdec381R116

2024-06-10 16:03 UTC, lavarou requested changes
PHPs 7.0 and 7.1 need to be deprecated before being EOLed.

2024-06-28 15:18 UTC, lavarou approved these changes

2024-07-12 19:59 UTC, ZNeumann approved these changes

2024-07-19 16:22 UTC, merged