chore: bump version to 11.0
newrelic/newrelic-php-agent pull request #943
Opened 2024-07-22 18:13 UTC by zsistla

Version bump to 11.0.0 for next release

2024-07-22 18:23 UTC, bduranleau-nr submitted a review, later dismissed

2024-07-22 19:00 UTC, ZNeumann approved these changes

2024-07-22 19:17 UTC, mfulb approved these changes

2024-07-22 19:18 UTC, mfulb requested changes
Is this supposed to go onto main?

2024-07-22 19:33 UTC, mfulb approved these changes

2024-07-23 00:10 UTC, lavarou approved these changes

2024-07-23 17:39 UTC, lavarou approved these changes

2024-07-25 12:55 UTC, merged